### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db-eventstore#21]
There aren't any, at the moment.

**Comment by haadcode** [comment]
Closing as wont-fix. See reasons in https://github.com/orbitdb/orbit-db-feedstore/issues/15#issuecomment-446173725.

**Comment by RichardLitt** [comment]
Let's add a note to the README about testing in this module. It's not clear to me looking only at this module that the tests aren't here.

**Comment by aphelionz** [comment]
Added a note to the README
