### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by ghost** [orbitdb/orbit-db-eventstore#36]
Will everyone see the same order?  as in, are these events ordered? I'm thinking about writing a custom store but it relies on knowing the order of events that occurred.

**Comment by aphelionz** [comment]
They are ordered. It's important to know though that they are ordered according to _logical_ clocks, not "wall time."

The entries are given numerical intger indexes: 1, 2, 3, etc. Then, the are also sorted by node ID so A1 B1 A2 B2 B3, etc...

Here's my explanation on YouTube, the bit on Conflict-free Replicated Data Types at  : https://youtu.be/x3yy_609rmM?t=590

**Comment by ghost** [comment]
Thank you for responding so quickly! Okay so it's using a vector clock + node Id under the hood, and eventually everyone will have the same ordering. Does that sound like the right takeaway or did I misunderstand? I think this might be right for my usage.

In any case, thank you so much for taking the time out to answer.

**Comment by aphelionz** [comment]
Yep, that's correct although I'd use "Lamport Clock" instead of Vector Clock. Overall you got the idea though :+1:

**Comment by aphelionz** [comment]
The aim is *strong eventual consistency* meaning that all the nodes will achieve the same state once they receive all the updates

**Comment by ghost** [comment]
heh, I'm still learning proper usage of the terms, which is a pretty strong indicator I have yet to solidify my knowledge of distributed systems. Strong eventual consistency is exactly what I'm looking for in my project. Again, thank you. I'll close this out.
